/**
 * UI Schema Types
 *
 * These types define the structure of mobile app UI specifications
 * that will be generated by the LLM and rendered in the browser.
 */

export type NodeType =
  | "screen"
  | "column"
  | "row"
  | "card"
  | "text"
  | "button";

export interface UINode {
  id: string;
  type: NodeType;
  props?: {
    text?: string;
    variant?: "title" | "subtitle" | "body";
    padding?: number;
    spacing?: number;
    align?: "start" | "center" | "end" | "space-between";
    backgroundColor?: string;
  };
  children?: UINode[];
}

export interface Screen {
  id: string;
  name: string;    // "Home", "AddHabit", etc
  route: string;   // "home", "add_habit", etc
  root: UINode;    // Root node with type "screen"
}

export interface AppDesignSpec {
  appName: string;
  theme: {
    primary: string;     // hex color like "#22c55e"
    background: string;  // hex color like "#020617"
  };
  screens: Screen[];
}
